### ISSUE TITLE
License and contact

### ISSUE THREAD

**Issue by kequach** [PeterLombaers/asreview-ranking-stability#1]
While examining this repository I noticed that there is no license added, as well as contact persons in case of questions. Since most of the asreview repositories use an Apache 2.0 license, I think this might also be a good fit here?
An example of how to use the code would also be good to add to the documentation.

**Comment by PeterLombaers** [comment]
Added license and contact in (38b3a88592e15a6925f3e843660484868c6d1f51). I left out a code example, because this can be implemented better in version 1 of asreview.
